### ISSUE TITLE
npm shrinkwrap fails when using patternfly and Node 4 LTS

### ISSUE THREAD

**Issue by krotscheck** [patternfly/patternfly-3#249] opened 2016-04-07 12:52 UTC
We have a project which uses patternfly, and we build this project using Node 4 and npm 2.4.17, the LTS versions soon to be available on xenial. As a debugging and security measure, we run npm shrinkwrap in the gate, which fails due to this project. The core reason appears to be that patternfly's npm-shrinkwrap.json file includes dev dependencies, which run into this bug here: https://github.com/npm/npm/issues/6298

vagrant@vagrant-ubuntu-trusty-64:~/tripleo-ui$ npm shrinkwrap --dev
npm ERR! Linux 3.13.0-85-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "shrinkwrap" "--dev"
npm ERR! node v4.4.2
npm ERR! npm  v2.14.7

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: connect-livereload@0.3.2 /home/vagrant/tripleo-ui/node_modules/patternfly/node_modules/connect-livereload
npm ERR! extraneous: grunt-jekyll@0.4.2 /home/vagrant/tripleo-ui/node_modules/patternfly/node_modules/grunt-jekyll
npm ERR! extraneous: grunt-contrib-connect@0.5.0 /home/vagrant/tripleo-ui/node_modules/patternfly/node_modules/grunt-contrib-connect
npm ERR! extraneous: grunt-contrib-uglify@0.3.3 /home/vagrant/tripleo-ui/node_modules/patternfly/node_modules/grunt-contrib-uglify
npm ERR! extraneous: grunt@0.4.5 /home/vagrant/tripleo-ui/node_modules/patternfly/node_modules/grunt
npm ERR! extraneous: grunt-css-count@0.3.0 /home/vagrant/tripleo-ui/node_modules/patternfly/node_modules/grunt-css-count
npm ERR! extraneous: grunt-contrib-watch@0.5.3 /home/vagrant/tripleo-ui/node_modules/patternfly/node_modules/grunt-contrib-watch
npm ERR! extraneous: matchdep@0.3.0 /home/vagrant/tripleo-ui/node_modules/patternfly/node_modules/matchdep
npm ERR! extraneous: grunt-jslint@1.1.14 /home/vagrant/tripleo-ui/node_modules/patternfly/node_modules/grunt-jslint
npm ERR! extraneous: grunt-contrib-less@1.0.1 /home/vagrant/tripleo-ui/node_modules/patternfly/node_modules/grunt-contrib-less
npm ERR! extraneous: grunt-contrib-cssmin@0.12.3 /home/vagrant/tripleo-ui/node_modules/patternfly/node_modules/grunt-contrib-cssmin
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/tripleo-ui/npm-debug.log
vagrant@vagrant-ubuntu-trusty-64:~/tripleo-ui$ node --version
v4.4.2
vagrant@vagrant-ubuntu-trusty-64:~/tripleo-ui$ npm --version
2.14.7

**Comment by andresgalante** [comment] 2016-05-15 19:00
@krotscheck thanks for reporting this.

@LHinson the RHMAP guys had a similar problem with shrinkwrap. Let's add an issue to take a look at it.

**Comment by LHinson** [comment] 2016-05-18 12:58
@andresgalante would be happy to add @krotscheck request to the PF Jira. I'm assuming this would be a SPIKE (a story to investigate and figure out resulting stories). What would be the verification conditions (i.e. what needs to be completed) of such a story?

**Comment by bleathem** [comment] 2016-05-18 19:57
It's not normal practice to include _devDependencies_ in the npm-shrinkwrap file.  Is anyone able to share the motivation for doing so?

**Comment by dlabrecq** [comment] 2016-05-18 20:13
Which version of PatternFly are you using? I don't see devDependencies npm-shrinkwrap.json (e.g., I don't see any grunt\* in npm-shrinkwrap.json for v3.3.5). When npm shrinkwrap was run, the devDependencies should not have been included because the --dev switch wasn't used.

**Comment by bleathem** [comment] 2016-05-18 20:34
Indeed, I'm not able to reproduce this locally.  Using patternfly@3.3.5 and the following package.json:

```
{
  "name": "npmtest",
  "version": "1.0.0",
  "dependencies": {
    "patternfly": "^3.3.5"
  },
  "devDependencies": {
    "grunt-contrib-uglify": "^1.0.1"
  }
}
```

then running `npm install` and `npm shrinkwrap --dev` returns successfully:

```
$ node -v
v4.4.2
$ npm -v
2.14.17
$ npm install
...
$ npm shrinkwrap --dev
wrote npm-shrinkwrap.json
```

Have you tried blowing away the npm-shrinkwrap file and re-running the shrinkwrap command?
Can you provide a simple package.json file that can be used to reproduce this error?

**Comment by andresgalante** [comment] 2017-02-03 18:44
@priley86 @bleathem Is this fixed? can we close this issue?

**Comment by dlabrecq** [comment] 2017-02-06 14:54
We run "npm prune --production" prior to creating the shrinkwrap, so the dev dependencies should no longer be included.

**Comment by krotscheck** [comment] 2017-02-08 23:54
There's two motivations to including devDependencies in the shrinkwrap file:

1. Transient devDependencies can result in broken build tools, thus creating a failing build.
2. Transient devDependencies can create variable build output, thus creating a non-reproducible build.

Having said that, I'm no longer working on OpenStack (which encountered this issue), so I'm going to disengage from this ticket. Good luck.

**Comment by andresgalante** [comment] 2017-03-13 18:32
@dlabrecq @priley86 @bleathem any news on this one?

**Closed as completed** 2017-10-13 13:00 UTC
Labels: waiting for reply/update, js
