### ISSUE TITLE
additional info items of list-view are in a chaos

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#586] opened 2017-02-10 05:40 UTC
![screenshot from 2017-02-10 10-47-01](https://cloud.githubusercontent.com/assets/5689075/22815407/13a2bf00-ef21-11e6-94d5-e5bd709955ce.png)

**Comment by andresgalante** [comment] 2017-03-13 18:07
This is a website issue. Also, I can't reproduce it. Is it fixed? can we close this issue?

**Closed as completed** 2017-10-25 11:15 UTC
Labels: waiting for reply/update
