### ISSUE TITLE
Step indicator numbers are not centered when changing base font size

### ISSUE THREAD

**Issue by spadgett** [patternfly/patternfly-3#659] opened 2017-06-02 20:16 UTC
We use a 13px base font size and notice the numbers inside the indicator bubbles are off center.

![openshift web console 2017-06-02 16-14-20](https://cloud.githubusercontent.com/assets/1167259/26743113/a2c6cdb2-47ae-11e7-903b-5db06394364c.png)

cc @jwforres @jeff-phillips-18

**Comment by michpetrov** [comment] 2017-06-05 10:13
FWIW, you can adjust the vertical position with line-height, in this case changing it to 21px seems to do the trick. (I don't think there's a way to make it universally centered for an arbitrary font-size)

**Comment by spadgett** [comment] 2017-06-05 12:06
@michpetrov Is it possible to calculate line height for the indicator relative to font-size-base? It looks like it's horizontally off-center as well.

We just changed the indicator number to 12px instead of using font-size base, which looks fine.

**Comment by michpetrov** [comment] 2017-06-05 13:34
@spadgett I don't think so, at least from what I tried, e.g. for sizes between 14 and 20 px the correct line height seems to be 20px, for larger sizes 18px looks better (even for something like 100px). 

As for the horizontal centering part of the problem is the font itself:
![screenshot from 2017-06-05 15-17-34](https://cloud.githubusercontent.com/assets/1999074/26785402/72f48a9c-4a02-11e7-82d5-27435653088a.png)
this is the 13px font-size but you can see the 2 has kind of a padding on both sides and since it's 8px it's going to be off by a pixel in a 25px container, whereas the 3 appears closer to the left despite being properly centered.

**Comment by andresgalante** [comment] 2017-08-16 14:05
@spadgett thanks for reporting this one an sorry for the delay. I can't reproduce it though 😞  What browser are you using?
Regarding this issue I think we can make a better use of calcs to make the markers more flexible.

<img width="479" alt="screen shot 2017-08-16 at 11 02 01 am" src="https://user-images.githubusercontent.com/1832037/29367209-83a92296-8272-11e7-9293-41715a5d1ee3.png">

Also thanks a lot @michpetrov for the help

**Comment by matthewcarleton** [comment] 2017-10-13 14:45
@spadgett Hi Sam, any update on this? Would love to get a bit more info (see @andresgalante question ^) to help get this resolved. Thanks!

**Comment by spadgett** [comment] 2017-10-13 16:28
I'm using Chrome.

@andresgalante I think you've reproduced it. It's subtle, but the numbers are a little to the right and too low. It might be worse for even larger font sizes though

**Comment by spadgett** [comment] 2017-10-13 16:28
Obviously not a huge issue, but I thought I'd report it since I noticed it.

Edit: I'm OK just closing the issue if it's too minor.

**Comment by andresgalante** [comment] 2017-10-24 18:03
@spadgett I'll close it for now and keep this noted to address it on PFNext

Thanks a lot for spotting it and bringing it up

**Closed as completed by andresgalante** 2017-10-24 18:03 UTC
Labels: css
